### PR TITLE
Heroku

### LINKED ISSUE #5: Heroku build & deploy
Solves problem with running and auto deploying/building app on heroku.

### PR DESCRIPTION
**Pull request by JanMikes**
Closes #5 

- [ ] Sqlite -> Postgre
- [x] Front controller for nginx (direct everything to index.php)
- [x] Fix whitepage
- [x] NPM buildpack
- [ ] Autodeploy on heroku for branch `master`

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Thanks bro :+1: 

What exactly was the issue line that fixed redirects?

**Comment by JanMikes** [comment]
Changes that needed to be done apart of changes you can see in this pr:

```
 heroku config:set APP_SECRET=tUDU6uTmkDg5ArRcvh3Dr56tTvkNT3Ag
 heroku buildpacks:set heroku/nodejs
 heroku buildpacks:set heroku/php --index 2
```

Note that `heroku config:set APP_ENV=prod`  was done already before.

**Comment by JanMikes** [comment]
Tbh i have no idea, the redirects worked for me without any change. I think it was browser cache or some other shit.

Other problems i could find out by running `heroku logs --tail`, which shows server logs, so i knew exactly what to fix (missing `ext-intl` in composer.json) and there was one more, missing env variable APP_SECRET:

screenshot 2018-08-16 23 55 15

**Comment by TomasVotruba** [comment]
The page still doesn't work for me: https://pehapkari-open-lecture.herokuapp.com/

image

Should I clear some cache?

**Comment by JanMikes** [comment]
I am almost sure this will get fixed after we set up deployment from heroku branch, i deployed manually now, please can you re-try?

**Comment by TomasVotruba** [comment]
It works :+1:  Thanks

**Comment by JanMikes** [comment]
It was a pleasure.

If there is anything else i can help you with regards the heroku, just ping me or add comment, i will stay subscribed to this 😉

**Review by TomasVotruba — COMMENTED** [review]
:+1:

**Pull request merged**
